# Generated by Django 5.2.4 on 2025-07-22 09:36

from django.db import migrations

# from models import Flat 


NEW_BUILDING_YEAR = 2015


def ge_building_year(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    flats = Flat.objects.only('id',
                              'construction_year',
                              'new_building').iterator(chunk_size=2000)
    for flat in flats:
        if flat.construction_year >= NEW_BUILDING_YEAR:
            flat.new_building = "True"
            flat.save()
        else:
            flat.new_building = "False"
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
       migrations.RunPython(ge_building_year),
    ]
