# Generated by Django 5.2.4 on 2025-07-22 09:55

from django.db import migrations


NEW_BUILDING_YEAR = 2015


def ge_building_year(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    flats = Flat.objects.all().iterator(chunk_size=500)
    for flat in flats:
        if flat.construction_year >= NEW_BUILDING_YEAR:
            flat.new_building = "True"
            flat.save()
        else:
            flat.new_building = "False"
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20250722_1236'),
    ]

    operations = [
       migrations.RunPython(ge_building_year),
    ]
