# Generated by Django 5.2.4 on 2025-07-23 07:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_complaintaboutflat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplaintAboutFlat',
            new_name='Complaint',
        ),
    ]
