# Generated by Django 5.2.4 on 2025-07-23 13:54
from django.db import migrations, transaction

import phonenumbers


def make_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    with transaction.atomic():
        flats = Flat.objects.only('id',
                                  'owners_phonenumber',
                                  'owner_pure_phone').iterator(chunk_size=2000)
        for flat in flats:
            try:
                flat.owner_pure_phone = phonenumbers.format_number(
                    phonenumbers.parse(
                        flat.owners_phonenumber,
                        "RU"), phonenumbers.PhoneNumberFormat.E164)
                flat.save()
            except phonenumbers.phonenumberutil.NumberParseException:
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(make_owner_pure_phone)
    ]
