# Generated by Django 5.2.4 on 2025-07-23 13:54

from django.db import migrations

import phonenumbers


def make_owner_pure_phone(apps, schema_editor):

    Flat = apps.get_model('property', 'Flat')
    # flats = Flat.objects.all()
    for flat in Flat.objects.all():
        flat.owner_pure_phone = phonenumbers.format_number(
            phonenumbers.parse(
                flat.owners_phonenumber,
                "RU"), phonenumbers.PhoneNumberFormat.E164)
        # flat.owner_pure_phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(make_owner_pure_phone)
    ]
