# Generated by Django 5.2.4 on 2025-07-24 08:37

from django.db import migrations


def make_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    flats = Flat.objects.all().iterator(chunk_size=500)
    for flat in flats:
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_owner'),
    ]

    operations = [
        migrations.RunPython(make_owners)
    ]
