# Generated by Django 5.2.4 on 2025-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20250724_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='apartments_owned',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', to='property.flat', verbose_name='Квартиры в собственности:'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер владельца:'),
        ),
    ]
