# Generated by Django 5.2.4 on 2025-07-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_owner_apartments_owned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='apartments_owned',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='owners', to='property.flat', verbose_name='Квартиры в собственности:'),
        ),
    ]
