# Generated by Django 5.2.4 on 2025-07-25 09:05

from django.db import migrations


def make_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    owner_map = {}

    for flat in Flat.objects.all():
        key = (flat.owner.strip(), flat.owners_phonenumber,
               flat.owner_pure_phone)

        if key not in owner_map:
            owner_obj, created = Owner.objects.get_or_create(
                owner=flat.owner.strip(),
                owners_phonenumber=flat.owners_phonenumber,
                owner_pure_phone=flat.owner_pure_phone,
            )
            owner_map[key] = owner_obj
        else:
            owner_obj = owner_map[key]

        flats = list(owner_obj.apartments_owned.all()) + [flat]
        owner_obj.apartments_owned.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_alter_owner_apartments_owned'),
    ]

    operations = [
        migrations.RunPython(make_owners)
    ]
