# Generated by Django 5.2.4 on 2025-07-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_alter_owner_owner_alter_owner_owner_pure_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
